### PR TITLE
Ablation Experiment Generation

### PR DESCRIPTION
**Pull request by rachitnigam**
Given a parameter file `params/mat-mul-params`, run:

```
python3 evaluation/ablation-exp-gen.py -p params/mat-mul-params -o exp-out -t 5 10
```

### CODE REVIEW

**Comment by avanhatt** [comment]
Can you give an example of the params file?

**Comment by rachitnigam** [comment]
```
{
  "A-rows": 10,
  "A-cols": 10,
  "B-rows": 10,
  "B-cols": 10,
  "reg-size": 4
}
```

**Comment by avanhatt** [comment]
Ah oops, I wasn't sure if the params was supposed to capture the range of experiments to run, but I see now that's passed as the other arguments. Sorry!

**Comment by avanhatt** [comment]
Works locally, merging

**Pull request merged**
